import React from "react";
import type { NextPage } from "next";
import Head from "next/head";

const PrivacyPolicy: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Privacy Policy</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="w-4/5 m-auto">
        <h1 className="font-raleway text-[28px] md:text-[36px] font-semibold leading-normal my-3 md:text-[28]">
          Privacy <span className="font-raleway text-skin-main">Policy</span>
        </h1>

        <p className="leading-6 text-sm md:text-base">
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minus
          accusantium repellendus nam laboriosam consectetur vero rem optio
          ipsam doloremque velit libero, ipsum impedit! Ea laborum sint deserunt
          non qui rem, corporis quidem sunt id nihil distinctio quibusdam
          voluptate placeat saepe maxime nam odit cumque. Voluptates nemo
          quibusdam aliquam! Fugiat nostrum, pariatur sit similique praesentium
          eaque officiis laborum saepe quia facere itaque, labore ipsa omnis
          laboriosam alias velit cum voluptatem aspernatur voluptas sunt
          deleniti! Aut deleniti, corrupti, placeat earum maiores dicta
          doloremque incidunt asperiores suscipit, unde inventore. Cum
          consequatur, sed adipisci voluptatum dolorem id dolor harum ducimus
          veritatis nisi, accusamus sit fuga voluptatibus eos vitae, praesentium
          magnam quaerat. Quia quis eius ea placeat, voluptas nihil? Placeat
          debitis eum minus nihil cum a nemo velit. Voluptatum, doloremque
          laudantium? Veniam culpa illum exercitationem obcaecati, cupiditate
          repellendus omnis porro modi ad reprehenderit doloribus tenetur amet
          quibusdam nesciunt dolor mollitia ratione magni accusamus quo
          sapiente! Ut ea voluptas ab dolor et facilis quibusdam, rerum
          excepturi? Lorem ipsum dolor sit, amet consectetur adipisicing elit.
          Quibusdam, consectetur officia? Recusandae minima repellendus aut
          distinctio inventore itaque magnam incidunt hic rerum animi harum
          consequuntur sequi iste aliquid commodi eveniet, dolorum iure id
          facilis saepe fugiat nulla temporibus! Totam in voluptas repellat. Sit
          corrupti magni delectus, laborum exercitationem aperiam beatae velit
          repellat ab, minima praesentium ratione excepturi debitis eaque?
          Quidem eum ullam nam atque qui natus. Nostrum, dolorum. Praesentium
          harum quos nostrum. Libero praesentium earum facilis itaque ipsam
          consectetur atque, doloribus autem iste ab et beatae odio dolorem
          veniam officia commodi illum consequatur porro obcaecati deserunt
          mollitia iure, voluptates recusandae eaque. Voluptates, labore libero
          laudantium temporibus nisi earum sequi ipsam. Lorem ipsum, dolor sit
          amet consectetur adipisicing elit. Ut laboriosam maiores omnis
          quibusdam ducimus nostrum at beatae praesentium corrupti voluptatibus
          voluptatem, aliquam suscipit excepturi assumenda? Suscipit laborum
          commodi ipsam odit, corrupti blanditiis itaque sit repudiandae optio
          magnam porro! Labore fugit amet exercitationem reiciendis ipsam sed
          harum, sunt voluptates quis quidem illo a doloribus, atque, accusamus
          aliquid. Necessitatibus laborum obcaecati quaerat repudiandae rem
          debitis nesciunt ad fugit tempora reiciendis esse et alias eveniet,
          quasi eaque ab dolor minus consequatur ut molestias nobis consequuntur
          officiis quo quis. Veniam dolorum vero hic temporibus, quam sunt quod
          voluptatum fuga, tempore alias odio. Eius cumque natus ratione
          blanditiis officia dicta itaque doloribus adipisci quidem quis culpa
          asperiores nam voluptas atque eaque, reiciendis fuga ipsum vitae
          pariatur mollitia? Quibusdam optio perspiciatis ratione hic assumenda
          consectetur sunt perferendis, distinctio iste voluptate quo nulla!
          Nemo dolore distinctio dignissimos cupiditate quos numquam animi iusto
          maxime, minima similique quibusdam, ducimus sequi ex ullam odio
          dolorum quae est aperiam sapiente qui asperiores dolorem minus! Optio
          quam esse id iusto assumenda? Odit ullam mollitia, eum voluptatibus
          quas eveniet dolorum asperiores amet iure? Fuga nihil iure labore,
          cupiditate optio, quasi facere ratione, rerum at magni nulla ipsa
          neque impedit ipsum in! Modi, veniam?
        </p>

        <h1 className="font-raleway text-[22px] md:text-[28px] font-semibold leading-normal my-3">
          About Data{" "}
          <span className="font-raleway text-skin-main">Security</span> :
        </h1>
        <p className="leading-6 text-sm md:text-base mb-14">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis
          velit fugiat atque? Dolorum sunt dolores libero quae blanditiis
          laborum perferendis modi, iure quis atque voluptas saepe accusamus
          autem cumque. Quo consequuntur tempora reprehenderit, explicabo sed,
          totam facere excepturi sequi sunt magni ad magnam placeat fugit?
          Beatae deserunt at voluptatibus magni quis ducimus inventore ex vero,
          cumque sed quam, tenetur impedit, consequatur odio accusamus unde
          laborum perspiciatis suscipit earum eligendi. Quisquam necessitatibus
          cum maiores, quidem cupiditate ipsam alias hic iste nihil perferendis
          aperiam recusandae, a modi exercitationem facilis corrupti! Sapiente
          reprehenderit suscipit, quod dignissimos itaque totam. Beatae facilis
          aspernatur quidem perferendis? Maiores libero a itaque fugiat? Dolores
          non sunt, laborum veniam est nihil illum, deserunt magni aliquam quos
          sit natus expedita nam aliquid, quibusdam numquam? Recusandae omnis
          nemo alias magnam consequatur. Deleniti nesciunt nobis reprehenderit
          temporibus sequi facere pariatur minus commodi quas error veniam, quae
          voluptas totam expedita recusandae rerum, maxime provident eos eum!
          Delectus voluptatum molestias repellendus ab aspernatur quae minima
          expedita placeat praesentium quas consequatur sapiente esse optio
          doloremque suscipit eaque tenetur blanditiis vitae amet, ratione
          fugiat! Qui quam sunt recusandae aliquid expedita, neque incidunt eius
          eos nemo mollitia minus voluptates laudantium esse est et vitae cumque
          culpa voluptatum.
        </p>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
