const collegeList = ["A. D. Patel Institute of Technology",
        "A.K.G. Engineering College",
        "A.R.J. College of Engineering and Technology",
        "ABES Engineering College",
        "ACE Engineering College",
        "AES American Embassy School",
        "AIMIT",
        "AIT",
        "AMC Engineering College",
        "APS College of Engineering",
        "AQJ College",
        "ASM Institute of Business Management and Research",
        "Aalim Muhammed Salegh College",
        "Aarupadai Veedu Institute of Technology",
        "Acharya Institute of Technology",
        "Acharya N.G. Ranga Agricultural University",
        "Acharya Nagarjuna Vishwavidhyalayamu",
        "Acropolis Institute of Technology and Research",
        "Acropolis Technical Campus",
        "Adhiyamaan College of Engineering",
        "Adi Shankara Institute of Engineering and Technology",
        "Adikavi Nannaya University",
        "Aditanar College of Arts and Science",
        "Aditya Institute of Technology and Management",
        "Advanced Institute of Technology and Management",
        "Agra College",
        "Ajmer Institute of Technology",
        "Akkineni Nageswara Rao College",
        "Al-Ameen Educational and Medical Foundation",
        "Alagappa University College of Education",
        "Alard Institute of Management Sciences (AIMS)",
        "Aligarh Muslim University",
        "All India Institute of Medical Sciences",
        "All Saints College of Technology",
        "All Saints  College",
        "Allahabad Agricultural Institute",
        "Allahabad University",
        "Allana Inistitute Of Management Sciences",
        "Allana Institute of Management Studies",
        "Alpha College of Engineering",
        "Amal Jyothi College of Engineering",
        "Ambala College of Engineering",
        "Ambedkar Institute of Technology",
        "American School of Bombay",
        "Amity School of Engineering and Technology - New Delhi",
        "Amity University Lucknow Campus",
        "Amity University Haryana",
        "Amrapali Institute of Management and Computer Applications",
        "Amrapali Institute of Technology and Sciences",
        "Amravati University",
        "Amrita Vishwa Vidyapeetham - Coimbatore",
        "Amrita Vishwa Vidyapeetham - Amritapuri",
        "Amrita Vishwa Vidyapeetham - Bangalore",
        "Amrita School of Arts and Sciences - Mysore",
        "Amrita School of Arts and Sciences - Kochi",
        "Amrutvahini College of Engineering",
        "Anand Institute of Higher Technology",
        "Anand Institute of Information Science",
        "Anbanathapuram Vahaira Charities College - A.V.C.",
        "Andhra University",
        "Angel College of Engineering and Technology",
        "Anil Neerukonda Institute of Technology and Sciences - ANITS",
        "Anja Polytechnic College",
        "Anjalai Ammal Mahalingam Engineering College",
        "Anjuman College of Engineering and Technology",
        "Anna University",
        "Annai Mathammal Sheela Engineering College",
        "Annai Teresa Magalir Palkalaikazhgam",
        "Annamacharya Institute of Technology and Sciences",
        "Annamalai University",
        "Anurag group of Institutions",
        "Apeejay College of Engineering",
        "Apeejay Institute of Technology",
        "Apex Institute of Management and Science",
        "Appa Institute of Engineering and Technology",
        "Arasu Engineering College",
        "Army Institute of Technology",
        "Arul Anandar College",
        "Arya College of Engineering and Information Technology",
        "Arya Institute of Engineering and Technology",
        "Aryabhatta Institute of Engineering and Management",
        "Asansol Engineering College",
        "Asia Pacific Institute of Information Technology",
        "Assam Agricultural University",
        "Assam Engineering College",
        "Assam University",
        "Atal Birahi Vajpayee Indian Institute of Information Technology and Management",
        "Atharva College of Engineering",
        "Atmiya Institute of Technology and Science",
        "Atria Institute of Technology",
        "Auden Technology and Management Academy",
        "Aurora P. G. College",
        "Aurora Engineering College",
        "Avanthi Institute of Engineering and Technology",
        "Avinashilingam Institute for Home Science and Higher Education for Women",
        "Awadhesh Pratap Singh Vishwavidyalaya",
        "Ayya Nadar Janaki Ammal College",
        "B P Poddar Institute of Management and Technology",
        "B. P. Poddar Institute of Management and Technology",
        "B. V. B. College of Engineering and Technology",
        "B.N. Mandal University",
        "B.S. Anangpuria Institute of Technology and Management",
        "B.V.B. College of Engineering and Technology",
        "B.V.C. Engineering College",
        "BBS College of Engineering and. Technology",
        "BK Birla Institue of Engineering and Technology",
        "BLDEACET",
        "BMS College of Engineering (BMSCE)",
        "BMS Institute of Technology (BMSIT)",
        "BNM Institute of Technology",
        "BSA College of Engineering and Technology",
        "BSA Crescent Engineering College",
        "Baba Banda Singh Bahadur Engineering College",
        "Baba Farid University of Health Sciences",
        "Baba Saheb Ambedkar Institute of Technology and Management",
        "Babaria Institute of Technology",
        "Babasaheb Bhimrao Ambedkar Bihar University",
        "Babasaheb Bhimrao Ambedkar University",
        "Babu Banarasi Das National Institute of Technology and Management",
        "Babu Banarsi Das Institute of Technology",
        "Babu Mohanlal Arya Smarak Engineering College",
        "Bahadhur Shastri National Academy of Administration",
        "Baharati Vidyapeeth College of Engineering",
        "Bahai Institute for Higher Education",
        "Baldev Ram Mirdha Institute of Technology",
        "Balaji Institute of Technology &amp; Science",
        "Banaras Hindu University",
        "Banarsidas Chandiwala Institute Of Information Technology",
        "Banasthali Vidyapith for Women",
        "Bangalore Institute of Technology",
        "Bangalore University",
        "Bankura Unnayani Institute of Engineering",
        "Bannari Amman Institute of Technology",
        "Bansal College of Engineering",
        "Bansal Institute of Science and Technology",
        "Bansal School of Engineering and Technology",
        "Bapuji Institute of Engineering and Technology",
        "Bapuji Institute of Hi-Tech Education",
        "Bapurao Deshmukh College of Engineering",
        "Barkatullah Vishwavidyalaya",
        "Basaveshwar Engineering College - Bagalkot",
        "Beant College of Engineering and Technology",
        "Bellary Engineering College",
        "Bengal College of Engineering and Technology",
        "Bengal Engineering College",
        "Bengal Engineering and Science University",
        "Bengal Institute of Technology",
        "Berhampur University",
        "Bhajarang Engineering College",
        "Bharat Institute of Technology",
        "Bharath Institute of Science and Technology",
        "Bharath Niketan Engineering College",
        "Bharathiar University",
        "Bharathidasan University",
        "Bharati Vidyapeeth",
        "Bharati Vidyapeeth Institute of Management and IT",
        "Bharati Vidyapeeth University Institute of Management and Research",
        "Bharatiya Vidya Bhavans S. P. Jain Institute of Management and Research (SPJIMR)",
        "Bhartiya Pashu-Chikitsa Anusandhan Sansthan",
        "Bhatkhande Music Institute",
        "Bhavnagar University",
        "Bhilai Institute of Technology",
        "Bhiwani Institute of Technology and Sciences",
        "Bhoj Reddy Engineering College for Women",
        "Bhoomaraddi College of Engineering and Technology (BVBCET)",
        "Bhopal Engineering College",
        "Bidhan Chandra Krishi Viswavidyalaya",
        "Bihar Yoga Bharati",
        "Biju Patnaik University of Technology",
        "Birbhum Institute of Engineering and Technology",
        "Birla Institute of Applied Science",
        "Birla Institute of Technology - Ranchi",
        "Birla Institute of Technology and Science - BITS Pilani",
        "Birla Institute of Technology",
        "Birsa Agricultural University",
        "Birsa Institute of Technology",
        "Bishop Heber College",
        "Biyani Institute of Science and Management - BISMA",
        "Brindavan College of Engineering",
        "Bundelkhand Institute of Engineering and Technology",
        "Bundelkhand University",
        "C K Pithawala College of Engineering and Technology",
        "C U Shah College of Engineering and Technology",
        "C.B. Patel Computer College",
        "CET Karnataka Information and Counselling",
        "CIT-Changa",
        "CMR College of Engineering Technology (CMRCET)",
        "CMR College of Engineering and Technology",
        "CMR Institute of Technology",
        "CSI College Of Engineering (CSICE)",
        "CV Raman College of Engineering",
        "CVR College of Engineering",
        "Calcutta Institute of Engineering and Management",
        "Calcutta Institute of Technology",
        "Canara Engineering College",
        "Chandubhai S Patel Institute of Technology",
        "Central Agricultural University",
        "Central Institute of English and Foreign Languages",
        "Central Institute of Fisheries Education",
        "Central Institute of Higher Tibetan Studies",
        "Centre for Development of Advanced Computing",
        "Centre for Environmental Planning and Technology",
        "Chaitanya Bharati Institute of Technology",
        "Chaityana Institute of Science and Technology",
        "Chamelidevi Institute of Technology and Management",
        "Chandigarh Engineering College",
        "Chandra Shekhar Azad University of Agriculture and Technology",
        "Chaudhary Charan Singh Haryana Agricultural University",
        "Chaudhary Charan Singh University",
        "Chaudhary Sarwan Kumar Himachal Pradesh Krishi Vishwavidyalaya",
        "Chennai Mathematical Institute",
        "Cherraans Arts and Science College",
        "Chettinad College of Engineering and Technology",
        "Chhattisgarh Swami Vivekanand Technical University",
        "Chhatrapati Shahu Ji Maharaj University",
        "Chhatrapati Shivaji Institute of Technoloty",
        "Chikhli College",
        "Chinmaya Institute of Technology",
        "Chitkara Educational Trust",
        "Chouksey Engineering College",
        "Christ College",
        "Christ University",
        "Christu Jayanthi Jubilee College",
        "Co-operative Institute of Technology - Vadakara",
        "Cochin University of Science and Technology - Kerala",
        "Coimbatore Institute of Engineering and Technology",
        "Coimbatore Institute of Technology",
        "College of Engineering and Management",
        "College of Engineering and Technology",
        "College of Engineering Kallooppara",
        "College Of  Engineering Karunagapally",
        "College of Engineering Poonjar",
        "College of Engineering Roorkee",
        "College of Engineering Thalassery",
        "College of Engineering Trivandrum",
        "College of Engineering",
        "College of Technology And Engineering",
        "Cummins College of Engineering for Women",
        "D. G. Ruparel College",
        "D.G. Vaishnav College - Chennai",
        "D.N.R College",
        "DAV College of Engineering and Technology",
        "DAV Institute of Engineering and Technology",
        "DB Pampa College",
        "DES Navinchandra Mehta Institute of Technology and Development",
        "DMCE Online",
        "DRK Institute of Science and Technology",
        "DVR college of Engineering and Technology",
        "Dadi Institute of Engineering and Technology",
        "Dakshina Bharat Hindi Prachar Sabha",
        "Darda Engineering College Yavatmal",
        "Dayalbagh Educational Institute",
        "Dayananda Sagar Institutions",
        "Deccan College of Engineering and Technology",
        "Deenbandhu Chhotu Ram University of Science and Technology",
        "Deendayal Upadhyay Gorakhpur University",
        "Deepshikha College of Technical Education",
        "Dehradun Institute of Technology",
        "Delhi College of Engineering",
        "Delhi University",
        "Delhi Vishwavidyalaya",
        "Deogiri College Aurangabad",
        "Dev Sanskriti Vishwavidyalaya",
        "Devanga Arts College",
        "Devi Ahilya Vishwavidyalaya",
        "Devineni Venkata Ramana and Dr. HS Mic College of Technology",
        "Dhanalakshmi College of Engineering",
        "Dharmsinh Desai University",
        "Dhirubhai Ambani Institute of Information and Communication Technology (DA-IICT)",
        "Dhruva College of Management",
        "Dibrugarh University",
        "Dnyaneswar Vidyapeeth IST ",
        "Doctor B.R. Ambedkar Open University",
        "Doctor Babasaheb Ambedkar Technological University",
        "Doctor Balasaheb Sawant Konkan Krishi Vidyapeeth",
        "Doctor Bhim Rao Ambedkar University",
        "Doctor Harisingh Gour Vishwavidyalaya",
        "Doctor Panjabrao Deshmukh Krishi Vidyapeeth",
        "Doctor Ram Manohar Lohia Awadh University",
        "Doctor Yashwant Singh Parmar University of Horticulture and Forestry",
        "Don Bosco Institute of Technology",
        "Dr G R Damodaran College of Science",
        "Dr MGR College",
        "Dr Mahalingam College of Engineering and Technology",
        "Dr Paul Raj Engineering College",
        "Dr. B.C. Roy Engineering College",
        "Dr. Babasaheb Ambedkar Marathwada University",
        "Dr. D. Y. Patil College of Engineering",
        "Dr. D. Y. Patil Institute Of Management and Research",
        "Dr. Kedar Nath Modi Institute of Engineering and Technology",
        "Dr. M.G.R Engineering College",
        "Dr. Navalar Nedunchezhian College Of Engineering",
        "Dr. Pauls Engineering College",
        "Dr. Ram Manohar Lohia Institute",
        "Dr. Sivanthi Aditanar College of Engineering",
        "Dr. T. Thimmaiah Institute of Technology",
        "Dr.M.G.R University",
        "Dravidian University",
        "Dronacharya College of Engineering",
        "Durgapur Institute of Advanced Technology and Management",
        "ERandDCI Institute of Technology",
        "East Point College of Engineering and Technology",
        "Easwari Engineering College",
        "Einstein College of Engineering",
        "Engineering College Ajmer",
        "Engineering College in Patiala",
        "Engineering College of Kota",
        "Engineering College",
        "Erode Sengunthar Engineering College",
        "Ethiraj College",
        "FET",
        "FORE School of Management",
        "Faculdades Integradas Logatti",
        "Fakir Mohan University",
        "Farah Institute of Computer Science",
        "Federal Institute of Science and Technology",
        "Fergusson College - Pune",
        "Feroz Gandhi Institute of Engineering and Technology",
        "Forest Research Institute",
        "Forte Institute of Technology",
        "Fr. Conceicao Rodrigues College of Engineering",
        "Future Institute of Engineering and Management",
        "Gujarat Forensic Science University",
        "G H Raisoni Institute of Information Technology",
        "G. B. Pant Engineering College - Uttar Pradesh",
        "G. D. Goenka World Institute - Lancaster University",
        "G. Narayanamma Institute of Technology and Science",
        "G. Pulla Reddy Engineering College",
        "G. Pullaiah College of Engineering and Technology",
        "G.H. Patel College of Engineering and Technology",
        "G.V.M. Institute of Technology and Management - GVMITM",
        "GATES Institute of Technology",
        "GLA Institute of Technology and Management",
        "GLS Institute of Computer Technology",
        "GMR Institute of Technology (GMRIT)",
        "Gnanamani College Of Engineering",
        "GS Medical College",
        "GVP College of Engineering",
        "Galgotia Institute of Management and Technology",
        "Galgotias College of Engineering and Technology",
        "Ganadipathy Tulsis Engineering College",
        "Gandhi Institute for Technology",
        "Gandhi Institute of Engineering and Technology (GIET)",
        "Gandhi Institute of Engineering and Technology",
        "Gandhi Institute of Technology and Management",
        "Gandhigram Rural Institute",
        "Ganpat University",
        "Garden City College",
        "Gauhati University",
        "Gauthami Degree College For Women",
        "Gayatri Vidya Parishad College of Engineering",
        "Geeta Institute Of Management And Technology",
        "Geetanjali Institute of Technical Studies",
        "Gitam Institute of Technology and Science",
        "Gitam University",
        "Gitarattan International Business School",
        "Global Academy of Technology",
        "Global Institute of Management and Technology (GIMT)",
        "Global Institute of Technology",
        "Goa Institute of Management",
        "Goa University",
        "Godavari Institute of Engineering and Technology",
        "Gogte Institute of Technology",
        "Gojan School of Business and Technology",
        "Gokaraju Rangaraju Institute of Engineering and Technology",
        "Gokhale Institute of Politics and Economics",
        "Gopal Ramalingam Memorial Engineering College",
        "Government College Of Engineering - Pune",
        "Government College of Arts",
        "Government College of Engineering",
        "Government College of Engineering Auranagabd",
        "Government College of Engineering and Ceramic Technology",
        "Government College of Engineering and Leather Technology",
        "Government College of Engineering",
        "Government Engineering College",
        "Government College of Technology",
        "Government Engineering College Ajmer",
        "Government Polytechnic Institute",
        "Government Polytechnic",
        "Govind Ballabh Pant Krishi Evam Praudyogik Vishwavidyalaya",
        "Govt. Mahila Engineering College",
        "Graphic Era Institute of Technology",
        "Great Lakes Institute of Management",
        "Greater Noida Institute of Technology",
        "Gudlavalleru Engineering College",
        "Gujarat Agricultural University",
        "Gujarat Ayurved University",
        "Gujarat University",
        "Gujarat Vidyapith",
        "Gulbarga University",
        "Gulzar Group Of Institutes",
        "Gurgaon Institute of Technology and Management",
        "Guru Ghasidas University",
        "Guru Gobind Singh College of Engineering and Technology",
        "Guru Gobind Singh Indraprastha University",
        "Guru Jambeshwar University",
        "Guru Nanak Dev University",
        "Guru Nanak Enginerring College",
        "Guru Ramdas Khalsa Institite of Technology",
        "Guru Tegh Bahadur Institute of Technology-GTBIT",
        "Gurukula Kangri Vishwavidyalaya",
        "Gurunanak Institute of Technology",
        "Gyan Ganga Institute of Technology and Sciences",
        "Gyan Vihar School of Engineering and Technology",
        "H.K.R.H. College",
        "HKBK College of Engineering",
        "HMS Institute of Technology",
        "Haldia Insitute of Technology",
        "Harcourt Butler Technological Institute - Kanpur",
        "Hemchandracharya North Gujarat University",
        "Hemwati Nandan Bahuguna Garhwal University",
        "Heritage Institute of Technology",
        "Hi-Point College of Engineering and Technology",
        "Himachal Pradesh University",
        "Hindustan College of Engineering",
        "Hindustan College of Science and Technology",
        "Hitkarini College of Engineering and Technology",
        "Holy Mary Institute of Technology and Science",
        "Hyderabad Central University",
        "IBS Ahmedabad",
        "IBS Hyderabad",
        "ICFAI Business School",
        "ICFAI National College",
        "ICFAI School of Information Technology",
        "ICFAI University",
        "IEC College of Engineering and Technology",
        "IMPS College of Engineering and Technology - IMPSCET",
        "IMS College Of Engineering",
        "INMANTEC Integrated Academy of Management and Technology",
        "Ilahia College of Engineering and Technology",
        "India Business School ",
        "Indian Agricultural Research Institute",
        "Indian Association for the Cultivation of Science",
        "Indian Business Academy",
        "Indian Institute of Foreign Trade",
        "Indian Institute of Information Management",
        "Indian Institute of Information Technology",
        "Indian Institute of Information Technology - IIIT Allahabad",
        "Indian Institute of Information Technology - IIIT Bangalore",
        "Indian Institute of Information Technology - IIIT Hyderabad",
        "Indian Institute of Information Technology - IIIT Kolkata",
        "Indian Institute of Information Technology - IIIT Pune",
        "Indian Institute of Information Technology Jabalpur",
        "Indian Institute of Information Technology and Management - Kerala",
        "Indian Institute of Information Technology and Management",
        "Indian Institute of Management",
        "Indian Institute of Rural Management",
        "Indian Institute of Science",
        "Indian Institute of Science and Information Technology",
        "Indian Institute of Science - IISc Bangalore",
        "Indian Institute of Science Education and Research Pune",
        "Indian Institute of Space Science and Technology",
        "Indian Institute of Social Welfare and Business Management",
        "Indian Institute of Technology - IIT Bhubaneswar",
        "Indian Institute of Technology - IIT Bombay",
        "Indian Institute of Technology - IIT Delhi",
        "Indian Institute of Technology - IIT Guwahati",
        "Indian Institute of Technology - IIT Kanpur",
        "Indian Institute of Technology - IIT Kharagpur",
        "Indian Institute of Technology - IIT Madras",
        "Indian Institute of Technology - IIT Powaii",
        "Indian Institute of Technology - IIT Roorkee",
        "Indian Institute of Technology - IIT Patna",
        "Indian Institute of Technology - IIT Ropar",
        "Indian Institute of Technology - IIT Hyderabad",
        "Indian Institute of Technology - IIT Gandhinagar",
        "Indian Institute of Technology - IIT Rajasthan",
        "Indian Institute of Technology - IIT Mandi",
        "Indian Institute of Technology - IIT Indore",
        "Indian Institute of Technology - IIT BHU",
        "Indian School of Business",
        "Indian School of Mines - Dhanbad",
        "Indian Statistical Institute",
        "Indira College of Engineering and Management",
        "Indira Gandhi Institute of Development and Research",
        "Indira Gandhi Institute of Technology",
        "Indira Gandhi Krishi Vishwavidyalaya",
        "Indira Gandhi National Open University",
        "Indira Gandhi Rashtriya Mukta Vishwavidyalaya",
        "Indira Institute of Management",
        "Indraprastha Institute of Information Technology",
        "Indira Kala Sangeet Vishwavidyalaya",
        "Indo Global Engineering",
        "Indore Institute of Science and Technology",
        "Indore Professional Studies Academy",
        "Indur Institute of Engineering and Technology",
        "Infant Jesus College of Engineering",
        "Institute of Informatics and Communication",
        "Institute for Development and Research in Banking Technology",
        "Institute for Electronic Governance",
        "Institute of Advanced Computer and Research",
        "Institute of Advanced Studies in Education",
        "Institute of Aeronautical Engineering",
        "Institute of Armament Technology",
        "Institute of Engineering and Science IPS Academy",
        "Institute of Engineering and Technology",
        "Institute of Foreign Trade and Management",
        "Institute of Industrial and Computer Management and Research A.T.S.S.  I.I.C.M.R.",
        "Institute of Information Technology and Management",
        "Institute of Management Research and Development",
        "Institute of Management Research",
        "Institute of Management Studies Career Development and Research",
        "Institute of Management Studies Noida",
        "Institute of Management Studies- Ghaziabad",
        "Institute of Management Technology",
        "Institute of Management and Research",
        "Institute of Mathematical Sciences - IMSc Chennai",
        "Institute of Productivity and Management",
        "Institute of Productivity and Management",
        "Institute of Road and Transport Technology",
        "Institute of Rural Management Anand",
        "Institute of Technology and Management",
        "Institute of Technology and Science (ITS)",
        "Institute of Technology and Marine Engineering",
        "Integral University",
        "International Institute for Population Sciences",
        "International Institute for Special Education",
        "International Institute of Information Technology",
        "International Institute of Management Science",
        "International Management Institute",
        "International School Of Informatics and Management",
        "International School of Business and Research",
        "International School of Business and Media",
        "International School of Informatics and Management",
        "International School of Information Management",
        "International School of Management Excellence",
        "Invertis Institute of Engineering and Technology",
        "Ishwarchand Vidya Sagar Institute of Technology and Management",
        "Islamiah Institute of Technology",
        "Islamic University of Science and Technology",
        "J.B. Institute of Engineering and Technology",
        "J.T. Mahajan College of Engineering",
        "Jay Sriram College of Technology",
        "JIS College of Engineering",
        "JM Institute of Technology",
        "JNTU College of Engineering",
        "JSPMs Abacus Institute Of Computer Application",
        "JSS Academy of Technical Education",
        "JSS College for Women",
        "Jabalpur Engineering College",
        "Jadavpur University - Jadavpur University",
        "Jagan Institute of Management Studies",
        "Jagan Nath University",
        "Jagannath Institute for Technology and Management",
        "Jagarlamudi Kuppuswamy Chowdary College",
        "Jai Narain Vyas University",
        "Jai Prakash Vishwavidyalaya",
        "Jain University",
        "Jaipur Engineering College and Research Centre",
        "Jaipur Engineering College",
        "Jaipuria Institute of Management",
        "Jamia Hamdard - Delhi",
        "Jamia Millia Islamia",
        "Jansons School of Business",
        "Jansons Institute of Technology",
        "Jawaharlal Institute of Technology",
        "Jawaharlal Nehru Centre for Advanced Scientific Research",
        "Jawaharlal Nehru Engineering College - JNEC",
        "Jawaharlal Nehru Krishi Vishwavidyalaya",
        "Jawaharlal Nehru Technological University",
        "Jawaharlal Nehru Technological University",
        "Jawaharlal Nehru University - JNU Delhi",
        "Jawaharlal Nehru Vishvavidyalaya",
        "Jaya College of Arts and Science",
        "Jaya Engineering College",
        "Jayam College of Engineering and Technology",
        "Jayawant Institute of Computer Applications",
        "Jayawant Shikshan Prasarak Mandal",
        "Jayawantrao Sawant College of Engineering",
        "Jaypee Institute of Information Technology",
        "Jaypee University of Information Technology",
        "Jaypee University of Engineering &amp; Technology",
        "Jehangirabad Institute of Technology",
        "Jeppiaar Engineering College",
        "Jerusalem College of Engineering",
        "Jind Institute of Engineering and Technology",
        "Jiwaji University",
        "Jnana Vikas Institute of Technology",
        "Jodhpur Engineering College and Research Centre",
        "Jodhpur Institute of Engineering and Technology",
        "Jorhat Engineering College",
        "Jyothi Engineering College",
        "Jyothi Nivas College",
        "Jyothishmathi Institute of Technology and Science",
        "K L University",
        "K. J. Somaiya College of Engineering",
        "K. K. Wagh Institute of Engineering Education and Research",
        "K. R. School of Information Technology",
        "K. S. R. College of Technology - Tamilnadu",
        "K.C. College of Engineering",
        "KCG College of Technology",
        "KGiSL Institute of Information Management",
        "KGiSL Institute of Technology",
        "KIIT College of Engineering",
        "KIIT University",
        "KLE Society College of Engineering and Technology",
        "KLN College of Engineering",
        "KLN College of Information Technology - KLNCIT",
        "KS Institute of Technology - KSIT",
        "KSR College of Technology",
        "KSRM College of Engineering",
        "KVM College of Engineering and Information Technology",
        "Kakatiya Institute of Technology and Science",
        "Kakatiya University",
        "Kakinada Institute of Engineering and Technology",
        "Kalasalingam University",
        "Kalikata Viswavidyalaya",
        "Kalinga Institute of Industrial Technology - Bhubaneshwar",
        "Kalyani Government Engineering College",
        "Kamala Institute of Technology and Science",
        "Kamaraj College of Engineering and Technology",
        "Kameshwar Singh Darbhanga Sanskrit University",
        "Kamla Nehru Institute of Technology - KNIT",
        "Kanchi Pallavan Enginnering College",
        "Kandula Sreenivasa Reddy Memorial College Of Engineering",
        "Kannada University",
        "Kannur University",
        "Kanpur Institute of Technology",
        "Karnatak University",
        "Karnataka State Open University",
        "Karpaga Vinayaga College of Engineering and Technology",
        "Karpagam Arts and Science College",
        "Karpagam College of Engineering",
        "Karpagam Institute of Technology",
        "Karpagam University",
        "Karunya University",
        "Kathir College of Engineering - KCE",
        "Kautilya Institute of Technology and Engineering",
        "Kavikulguru Institute of Technology and Science",
        "Kavikulguru Kalidas Sanskrit Vishwavidyalaya",
        "Kedar Nath Ginni Devi Modi Engineering College",
        "Kelkar Education Trust Vinayak Ganesh Vaze College",
        "Kerala University",
        "Kerala Agricultural University",
        "Keshav Mahavidyalaya",
        "Keshav Memorial Institute of Technology",
        "Khadir Mohideen College",
        "Khalsa College for Women",
        "Kings College of Engineering",
        "Kings Engineering College",
        "K.I.T College Of Engineering",
        "Koneru Lakshmaiah College of Engineering",
        "Kongu Arts and Science College",
        "Kongu Engineering College",
        "Kongunadu Arts and Science College",
        "Kota Open University",
        "Koti Womens College",
        "Krishna Engineering College",
        "Krishna Institute of Engineering and Technology",
        "Krishnasamy College of Engineering and Technology",
        "Kristu Jyothi College of Management and Technology",
        "Kumaraguru College of Technology - KCT",
        "Kumaun University",
        "Kurukshetra University - Haryana",
        "Kuvempu University",
        "LBS Institute of Technology for Women",
        "LBS PG College",
        "LD College of Engineering",
        "LDRP Institute of Technology and Research",
        "LJ Institute of Computer Applications - LJMCA",
        "Lady Shriram CC",
        "Lakshmi Narain College of Technology - LNCT",
        "Lakshmibai National Institute of Physical Education",
        "Lal Bahadur Shastri Institute of Management",
        "Lala Lajpat Rai Institute of Engineering and Technology",
        "Lalit Narayan Mithila University",
        "Larsen and Toubro Institute of Technology",
        "Late Bhausaheb Hiray S.S.Trusts College of Architecture",
        "Laxmi Devi Institute of Engineering and Technology",
        "Laxmi Niwas Mittal Institute of Information Technology",
        "Les Filles MVN Institute of Engineering and Technology",
        "Lokamanya Tilak PG College",
        "Lokmanya Tilak College of Engineering",
        "Lovely Professional University",
        "Loyola College - Chennai",
        "Loyola Institute of Business Administration",
        "Ludhiana College of Engineering and Technology - LCET",
        "M. S. Ramaiah Institute of Technology - Bangalore",
        "M.S. Engineering College",
        "MCKV Institute of Engineering",
        "MDS University",
        "MEASI Institute of Information Technology",
        "MES College of Engineering",
        "MES College",
        "MET Institute of Computer Science",
        "MET Institute of Engineering",
        "MET Institute of Management",
        "MGM College of Engineering and Technology",
        "MH Saboo Siddik College of Engineering",
        "MIT College of Engineering",
        "MIT School of Telecom and Management Studies",
        "MITS School of Biotechnology - MSB",
        "MK Institute of Computer Studies",
        "MLR Institute of Technology",
        "MLV Textile and Engineering College",
        "MRD Arts and E E Laher Kosadia Commerce College",
        "MVSR Engineering College",
        "Maamallan Institute of Technology",
        "Madanapalle Institute of Technology and Science",
        "Madha Engineering College",
        "Madhav Institute of Technology and Science",
        "Madhira Institute of Technology and Sciences",
        "Madhya Pradesh Bhoj (Open) University",
        "Madina Engineering College",
        "Madras Institute of Technology",
        "Madurai Kamaraj University",
        "Magadh University",
        "Magnus School of Business",
        "Maha College of Engineering",
        "Mahakal Institute of Technology and Science",
        "Maharaj Vijayaram Gajapath Raj College of Engineering",
        "Maharaja Agrasen Institute of Technology",
        "Maharaja Engineering College",
        "Maharaja Institute of Technology",
        "Maharaja Ranjit Singh College of Professional Sciences - MRS",
        "Maharaja Surajmal Institute of Technology",
        "Maharana Pratap Engineering College",
        "Maharana Pratap University of Agriculture and Technology",
        "Maharashtra Academy of Engineering",
        "Maharashtra Animal and Fishery Sciences University",
        "Maharashtra Institute of Technology (MIT)",
        "Maharashtra University of Health Sciences",
        "Maharishi Arvind Institute of Engineering and Technology",
        "Maharishi Arvind Institute of Science and Management - MAISM",
        "Maharishi Mahesh Yogi Vedic Vishwavidyalaya",
        "Maharshi Dayanand Saraswati University",
        "Maharshi Dayanand University",
        "Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalaya",
        "Mahatma Gandhi Chitrakoot Gramodaya Vishwavidyalaya",
        "Mahatma Gandhi Institute of Technology - MGIT",
        "Mahatma Gandhi Kashi Vidyapeeth",
        "Mahatma Gandhi Memorial Medical College",
        "Mahatma Gandhi University",
        "Mahatma Jyotiba Phule (MJP) Rohilkhand University",
        "Mahatma Phule Krishi Vidyapeeth",
        "Mahaveer Institute of Science and Technology",
        "Mahendra Engineering College",
        "Maheshwara Engineering College",
        "Mailam Engineering College",
        "Makhanlal Chaturvedi Rashtriya Patrakarita Vishwavidhyalaya",
        "Malankara Catholic College",
        "Malaviya National Institute of Technology",
        "Malla Reddy College of Engineering and Technology",
        "Malla Reddy Engineering College",
        "Mallabhum Institute of Technology",
        "Malnad College of Engineering",
        "Malout Institute of Management and Information Technology",
        "Management Development Institute",
        "Management Education and Research Institute",
        "Manav Rachna College of Engineering",
        "Mandsaur Institute of Technology",
        "Mangalmay Institute of Management and Technology",
        "Mangalore University",
        "Mangalore Institiute of Technology and Engineering",
        "Manipal Academy of Higher Education",
        "Manipur University",
        "Manjara Charitable Trust Rajiv Gandhi Institute of Technology",
        "Manonmaniam Sundaranar University",
        "Mar Athanasius College of Engineering",
        "Mar Thoma Institute of Information Technology - MIIT",
        "Marathwada Institute of Technology Bulandshahr",
        "Marathwada Krishi Vidyapeeth",
        "Marathwada Mitra Mandal College of Engineering",
        "Marian Engineering College",
        "Marine Engineering College - MERI",
        "Marudhar Engineering College",
        "Matrusri Institute of Post Graduate Studies",
        "Maulana Azad College",
        "Maulana Azad College",
        "Maulana Azad National Institute of Technology",
        "Maulana Azad National Urdu University",
        "Medicaps Institute of Technology and Management",
        "Meenakshi College for Women",
        "Meenakshi Sundararajan Engineering College",
        "Meerut Institute of Engineering and Technology",
        "Meghnad Saha Institute of Technology",
        "Mepco Schlenk Engineering College",
        "Military College of Telecommunication Engineering",
        "Misrimal Navajee Munoth Jain Engineering College",
        "Mizoram University",
        "Model Institute of Engineering and Technology",
        "Model Engineering College",
        "Modi Institute of Technology",
        "Mody Institute of Technology and Science",
        "Mohamed Sathak A.J. College of Engineering",
        "Mohan Lal Sukhadia University",
        "Mohandas College of Engineering and Technology",
        "Mohanlal Sukhadia University - MLSU",
        "Mona College of Engineering and Technology",
        "Moolji Jaitha College",
        "Mother Teresa Institute of Management",
        "Motilal Nehru National Institute of Technology",
        "Mount Carmel College",
        "Mudra Institute of Communications",
        "Muffakham Jah College of Engineering and Technology",
        "Mugniram Bangur Memorial Engineering College",
        "Mukesh Patel School of Technology Management and Engineering",
        "Mumbai Educational Trust (MET)",
        "Munnar Engineering College",
        "Murshidabad College of Engineering and Technology",
        "Mysore Medical College &amp; Research Institute",
        "NBKR Institute of Science and Technology",
        "NERIST",
        "NLCPAS Navsari",
        "NMAM Institute of Technology",
        "NMKRV College",
        "NRI Institute of Information",
        "NRI Institute of Technology",
        "NTR University of Health Sciences Andhra Pradesh",
        "Nadar Mahajana Sangam S.Vellaichamy Nadar College",
        "Nagaland University",
        "Nagarjuna College of Engineering and Technology",
        "Nagarjuna University",
        "Nagpur University",
        "Nalanda Institute of Engineering and Technology",
        "Nalanda Khula Vishwavidyalaya",
        "Nalla Malla Reddy Engineering College",
        "Nallamuthu Gounder Mahalingam College",
        "Nandha Engineering College - Erode",
        "Narasu Sarathy Institute of Technology",
        "Narayana Engineering College",
        "Narendra Deva University of Agriculture and Technology",
        "Nargund College of Pharmacy",
        "Narmada College of Computer Application",
        "Narsee Monjee Institute of Management and Higher Studies",
        "Narula Institute of Technology",
        "National Academy of Legal Studies and Research University",
        "National Dairy Research Institute",
        "National Engineering College",
        "National Institute of Construction Management and Research",
        "National Institute of Cooperative Management",
        "National Institute of Design",
        "National Institute of Engineering",
        "National Institute of Engineering (NIE) Mysore",
        "National Institute of Fashion Technology",
        "National Institute of Industrial Engineering",
        "National Institute of Information Technology",
        "National Institute of Mental Health and Neuro Sciences",
        "National Institute of Pharmaceutical Education and Research",
        "National Institute of Science and Technology",
        "National Institute of Technology Calicut (NITC)",
        "National Institute of Technology Durgapur",
        "National Institute of Technology Hamirpur",
        "National Institute of Technology Karnataka",
        "National Institute of Technology Kurukshetra",
        "National Institute of Technology Meghalaya",
        "National Institute of Technology Silchar",
        "National Institute of Technology Warangal",
        "National Institute of Technology Trichy",
        "National Institute of Technology ",
        "National Insurance Academy (NIA)",
        "National Law Institute University",
        "National Law School of India University",
        "National Law University",
        "Nehru College of Management",
        "Nelson Marlborough Institute of Technology",
        "Netaji Subhas Institute of Technology - Delhi",
        "Netaji Subhas Open University",
        "Netaji Subhash Engineering College - NSEC",
        "Neville Wadia Institute of Management Studies and Research",
        "New Horizon College of Engineering",
        "Nirma Institute of Technology",
        "Nirma University of Science and Technology",
        "Nishitha College of Engineering and Technology",
        "Nishitha PG College",
        "Nitte Meenakshi Institute of Technology",
        "Nizams Institute of Medical Sciences",
        "Noble Institute of Science and Technology",
        "Noida Institute Of Enginnering And Technology",
        "Noorul Islam College of Engineering",
        "Nootan Sarva Vidyalaya Sanchalit MCA College",
        "North Gujarat University",
        "North Maharashtra University",
        "North Orissa University",
        "Northwood High School",
        "North-Eastern Hill University",
        "Northern India Engineering College",
        "Nova College of Engineering and Technology",
        "N.S.S College of Engineering",
        "O. U. College for Women",
        "Oriental Institute of Science and Technology",
        "Orissa University of Agriculture and Technology",
        "Osmania University",
        "Oxford College of Engineering",
        "Oxford Engineering College",
        "P. A. College of Engineering",
        "Palakkad Institute of Science and Technology",
        "P. E. S. College of Engineering",
        "P. S. R. Engineering College",
        "P. V. P. Siddhartha Engineering College",
        "P.B.R. Visvodaya Institute of Technology and Science",
        "P.C. Jabin Science College",
        "P.E. Society Modern College of Engineering",
        "P.E.S. College Of Engineering",
        "P.G. College",
        "PDM College of Engineering",
        "PRRM Engineering College",
        "PSG College of Arts and Science",
        "PSG College of Technology",
        "PSNA College of Engineering and Technology",
        "Paavai Engineering College",
        "Pachaiyappas College",
        "Dr. D. Y. Patil Institute of Master of Computer Applications",
        "Dr D. Y. Patil Vidyapeeth",
        "BVRIT",
        "Padre Conceicao College of Engineering",
        "Pailan College of Management and Technology",
        "Pandit Ravishankar Shukla University",
        "Pandian Saraswathi yadava Engineering College",
        "Panimalar Engineering College",
        "Panipat Institute of Textile and Engineering",
        "Panjab University",
        "Park College of Engineering and Technology",
        "Parul Institute of Engineering and Technology",
        "Patel College Of Science and Technology",
        "Patna University",
        "Peoples Education Society Institute of Technology - PESIT",
        "Peoples Educational Soceity School of Engineering",
        "Periyar Maniammai College of Technology for Women",
        "Periyar University",
        "Pimpri Chichwad Polytechnic",
        "Pimpri Chinchwad College of Engineering",
        "Poddard International College",
        "Pondicherry Engineering College",
        "Pondicherry University",
        "Ponjesly College of Engineering",
        "Poona College",
        "Poornima College of Engineering",
        "Poornima Institute of Engineering and Technology",
        "Postgraduate Institute of Medical Education and Research",
        "Potti Sreeramulu Telugu University",
        "Pragati Engineering College",
        "Prakasam Engineering College",
        "Pranveer Singh Institute of Technology",
        "Prestige Institute of Management Dewas",
        "Priyadarshini College of Engineering",
        "Pune Institute of Computer Technology",
        "Pune Vidhyarthi Grihas College of Engineering and Technology",
        "Punjab Agricultural University",
        "Punjab College of Engineering and Technology",
        "Punjab Engineering College",
        "Punjab Technical University",
        "Punjab University - Chandigarh",
        "Punjabi University Neighbourhood Campus",
        "Punjabi University Patiala",
        "Pydah Engineering College",
        "QIS College of Engineering and Technology",
        "R. C. Patel Institute of Technology",
        "R. D. Gardi Medical College",
        "R. M. K. Engineering College",
        "R. N. S. Institute of Technology",
        "R. V. College of Engineering - Bangalore",
        "R. V. S. College of Arts and Science",
        "R. V. S. College of Engineering and Technology",
        "R.P.Sharma Institute of Technology",
        "RCC Institute of Information Technology",
        "RL Jalappa Institute of Technology",
        "RMD Engineering College",
        "RV College of Engineering",
        "RVR and JC College Of Engineering",
        "Rabindra Bharati University",
        "Radha Govind Engineering College",
        "Raghu Engineering College",
        "Raipur Institute Of Tecnology",
        "Raja College of Engineering",
        "Raja Mahendra College of Engineering",
        "Rajagiri School of Engineering and Technology",
        "Rajalakshmi Engineering College",
        "Rajarambapu Institute of Technology",
        "Rajarshi Shahu College Of Engineering - RSCOE",
        "Rajasthan Agricultural University",
        "Rajasthan College of Engineering For Women",
        "Rajasthan Institute Of Engineering and Technology",
        "Rajasthan Sanskrit Vishwavidyalaya",
        "Rajasthan Vidyapeeth",
        "Rajeev Gandhi Memorial College Of Engineering and Technology",
        "Rajeev Gandhi Institute of Technology",
        "Rajeev Gandhi Technical University",
        "Rajendra Agricultural University",
        "Rajiv Academy For Technology And Management",
        "Rajiv Gandhi Institute of Technology",
        "Rajiv Gandhi Proudyogiki Vishwavidyalaya",
        "Rajiv Gandhi University of Health Sciences",
        "Rajiv Gandhi University of Knowledge Technologies",
        "Rajlalakshmi Engineering College",
        "Ramnarain Ruia College for Arts and Science",
        "Ramrao Adik Institute of Technology - Navi Mumbai",
        "Ranchi University",
        "Ranganathan Engineering College",
        "Rani Durgavati Vishwavidyalaya",
        "Rashtriya Sanskrit Vidyapeetha",
        "Rashtriya Vidyalaya College of Engineering - RVCE",
        "Rayat Institute of Engineering and Information Technology",
        "Rayat and Bahra Institute of Engineering and Bio-Technology",
        "Regency Institute of Technology",
        "Regional Engineering College",
        "Reva Institute of Technology and Management",
        "Rishiraj Institute of Technology",
        "Rizvi College Of Arts",
        "Roland Institute of Technology",
        "Royal School of Management and Technology",
        "Rukmani Devi Institute of Advanced Studies - RDIAS",
        "Rungta College of Engineering and Technology",
        "Rural Engineering College",
        "Rustamji Institute of Technology - RJIT",
        "S V Institute of Computer Studies",
        "S. K. Patel Institute of Management and Computer Studies",
        "S.R.M.S. College of Engineering and Technology - Bareilly",
        "S. Sukhjinder Singh Engineering and Technology College",
        "S.D. Sabha Institute Of Technology",
        "S.I.E.S. College of Management Studies (SIESCOMS)",
        "S.K.R. Engineering College",
        "S.P. Chowgule College",
        "S.R. Engineering College",
        "S.V.H. College of Engineering",
        "S.V.K.P And Dr K.S. Raju Arts And Science College",
        "S.V.P.M College Of Engineering Malegaon (Bk)",
        "SACS MAVMM Engineering College",
        "SASTRA University",
        "SCSVMV",
        "SCT Institute of Technology",
        "SD College",
        "SDM College of Engineering and Technology",
        "SDP College for Women",
        "SGGS College of Engineering and Technology",
        "SHM Engineering College",
        "Shobhit University Meerut",
        "SIBER College",
        "SJM Institute of Technology",
        "SLBS Engineering College",
        "SLC Institute of Engineering and Technology",
        "SN Kansagra School",
        "SNS College of Engineering",
        "SP Jain Institute of Management and Research",
        "SR Engineering College",
        "SRK Institute of Technology",
        "SRM Engineering College",
        "SRM University",
        "SS Institute of Technology - Hyderabad",
        "SS Jain Subodh College",
        "SSJ Engineering College - Sri Sai Jyothi Engineering College",
        "SSM College of Engineering",
        "SSN College of Engineering",
        "ST. Peters Engineering College",
        "St. Thomas College Of Engineering &amp; Technology",
        "STJ Institute of Technology",
        "SUS College of Engineering and Technology",
        "SVKP and Dr. Kalidindi Suryanarayana Raju Arts and Science College",
        "Sagi Ramakrishnam Raju Engineering College - SRKR",
        "Sahrdaya College of Engineering and Technology",
        "Sai-Sudhir Post Graduate College",
        "Sakthi Mariamman Engineering College - SMEC",
        "Sambalpur University",
        "Sambhram Institute of Technology",
        "Sampurnanand Sanskrit Vishwavidyalaya",
        "Samrat Ashok Technological Institute Vidisha - SATI",
        "Sanjay Gandhi Memorial Government Polytechnic",
        "Sanjay Gandhi Postgraduate lnstitute of Medical Sciences",
        "Sankalchand Patel College of Engineering",
        "Sankara College",
        "Sanketika Vidya Parishad Engineering College",
        "Sant Gadge Baba Amravati University",
        "Sant Longowal Institiute of Engineering and Technology",
        "Sapthagiri College of Engineering",
        "Saranathan College of Engineering",
        "Sardar Patel College of Engineering - Mumbai",
        "Sardar Patel Institute of Technology - Mumbai",
        "Sardar Patel University",
        "Sardar Vallabhbai Polytechnic College",
        "Sardar Vallabhbhai National Institute of Technology",
        "Saroj Mohan Institute of Technology",
        "Sarva Vidhyalaya Institute of Computer Studies",
        "Sarvajanik College of Engineering",
        "Sasi Institute of Technology and Engineering",
        "Sathyabama Engineering College - Chennai",
        "Sathyabama Institute of Science and Technology",
        "Sathyabama University",
        "Satpriya Institute of Engineering and Technology",
        "Saurashtra University",
        "Saveetha Engineering College",
        "School of Planning and Architecture",
        "Scient Institute of Technology",
        "Seacom Engineering College",
        "Seth Rajiv Govind Sable Institute Of Technology",
        "Sethu Institute of Technology",
        "Shadan College of Engineering and Technology",
        "Shadan Womens College of Engineering and Technology",
        "Shankara Institute of Technology",
        "Shanmuganathan Engineering College",
        "Shanmugha Arts",
        "Shanmugha College of Engineering - Tamilnadu",
        "Shantilal Shah Engineering College",
        "Sharda University",
        "Shekhawati Engineering College",
        "Shivaji University",
        "Shree Rayeshwar Institute of Engineering and IT",
        "Shree Sant Muktabai Institute of Technology - SMIT",
        "Shreemati Nathibai Damodar Thackersey Womens University",
        "Shri Andal Alagar College of Engineering",
        "Shri Balaji College of Engineering and Technology",
        "Shri Govindram Seksaria Institute of Technology and Science",
        "Shri Guru Gobind Singhji College of Engineering and Technology",
        "Shri Guru Ram Rai Institute of Technology and Science",
        "Shri Hanuman Vyayam Prasarak Mandals College of Engg and Tech",
        "Shri Jagannath Sanskrit Vishwavidyalaya",
        "Shri Lal Bahadur Shastri Rashtriya Sanskrit Vidyapeeth",
        "Shri Mata Vaishno Devi University",
        "Shri Ram Murti Smarak College of Engineering",
        "Shri Ramdeobaba Kamla Nehru College",
        "Shri Ramswaroop Memorial College of Engineering and Management",
        "Shri Sant Gajanan Maharaja College of Engineering - SSGM",
        "Shri Vaishnav Institute of Technology and Science",
        "Shri Venkteshwar Institute Of Technology",
        "Shri Vishnu Engineering College for Women",
        "Shrimad Rajchandra Institute of Management and Computer Application",
        "Shrinathji Institute of Technology and Engineering",
        "Siddaganga Institute  of Technology",
        "Siddharth Institute of Engineering and Technology - SIETK",
        "Siddhu Kanhu Murmu University",
        "Sikkim Manipal University of Health",
        "Sinhgad Academy of Engineering",
        "Sinhgad College of Engineering - SCOE",
        "Sinhgad Institute of Management and Computer Application",
        "Sinhgad Institute of Technology",
        "Sinhgad Technical Educational Society - Pune",
        "Sinhudurg Shikshan Prasarak Mandals College of Engineering",
        "Sipnas College of Engineering and Technology",
        "Sir C R Reddy College of Engineering",
        "Sir M. Visvesvaraya Institute of Technology",
        "Sir Padampat Singhania University",
        "Sir Visvesvaraya Memorial Engineering College",
        "Smt Kashibai Navale College Of Engineering",
        "Smt Kasturbai Walchand College",
        "Smt Parvatibai Chowgule College",
        "Kamala and Venkappa M. Agadi College of Engineering and Technology",
        "SNDT Women's University",
        "Sobhasaria Engineering College",
        "Sona College of Technology",
        "Sophia Girls College Ajmer",
        "Sourashtra College",
        "South Gujarat University - Surat",
        "South Travancore Hindu College",
        "Sphoorthy Engineering College",
        "Sree Chaitanya College of Engineering",
        "Sree Chitra Tirunal Institute for Medical Sciences and Technology",
        "Sree Dattha Institute of Engineering",
        "Sree Narayana Guru Institute of Science and Technology",
        "Sree Sankaracharya University of Sanskrit",
        "Sree Sastha Engineering College",
        "Sreenidhi Institute of Science and Technology",
        "Sreenivasa Institute of Technology and Management Studies",
        "Sri Balaji College of Engineering and Technology",
        "Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya",
        "Sri Datta College of Engineering and Science - SDITS",
        "Sri Devi Womens Engineering College",
        "Sri Indu College of Engineering and Technology",
        "Sri Jagadguru Balagangadaranath swamiji Institute of Technology",
        "Sri Jagadguru Chandrasekaranathaswamiji Institute of Technology",
        "Sri Jayachamarajendra College of Engineering",
        "Sri Kaliswari College",
        "Sri Krishna College of Engineering and Technology (SKCET)",
        "Sri Krishnadevaraya University",
        "Sri Manakula Vinayagar Engineering College",
        "Sri Muthukumaran Institute of Technology",
        "Sri Padmavati Mahila Viswavidyalayam",
        "Sri Prakash College of Engineering Tuni",
        "Sri Ramachandra Medical College and Research Institute",
        "Sri Ramakrishna Engineering College",
        "Sri Ramakrishna Mission Vidyalaya College of Arts and Science",
        "Sri Ramanujar Engineering College",
        "Sri Sarathi Institute of Engineering and Technology",
        "Sri Sathya Sai Institute of Higher Learning",
        "Sri Shakthi Institute of Engineering and Technology",
        "Sri Siddhartha Institute of Technology",
        "Sri Sivasubramaniya Nadar College of Engineering",
        "Sri Vasavi Engineering College",
        "Sri Venkatesa Perumal College of Engineering and Technology",
        "Sri Venkateswara College of Engineering",
        "Sri Venkateswara University",
        "Sri Vidyaniketan Engineering College",
        "Srikalahasteeswara Institute of Technology",
        "Srimad Andavan Arts and Science College",
        "Srinivas Institute of Technology-Mangalore",
        "Srinivasa Institute of Engineering and Technology",
        "Srinivasan Engineering College",
        "Sriram Engineering College",
        "St Anns College of Engineering",
        "St Josephs College of Engineering",
        "St Patricks PG College",
        "St Stephen",
        "St. Francis Institute of Technology",
        "St. Johns College of Engineering and Techonology",
        "St. Josephs College (Autonomous) - Tiruchirappalli",
        "St. Margaret Engineering College - Neemrana",
        "St. Martins Engineering College",
        "St. Marys Engineering College",
        "St. Theressa Institute of Engineering and Technology",
        "St. Vincent Pallotti College",
        "St. Xaviers College",
        "St.Xaviers Catholic College of Engineering",
        "SAINTGITS COLLEGE OF ENGINEERING",
        "Stani Memorial College of Engineering and Technology",
        "Sudharsan Engineering College",
        "Sushila Devi Bansal College of Technology",
        "Swami Keshvanand Institute of Technology",
        "Swami Parmanand College of Engineering and Technology",
        "Swami Ramanand Teerth Marathwada University",
        "Swami Ramananda Tirtha Institute of Science and Technology",
        "Swami Sachchidanand Polytechnic College Visnagar",
        "Swami Sahajanand College of Commerce And Management",
        "Swami Vivekananda PG College",
        "Swarnandhra College of Engineering",
        "Symbiosis",
        "T.K.M. College of Engineering",
        "TERI School of Advanced Studies",
        "TRR College of Engineering",
        "Techno India Salt Lake",
        "TRUBA Institute of Engineering and Information Technology",
        "Tagore Engineering College",
        "Tamil Nadu Agricultural University",
        "Tamil Nadu Doctor Ambedkar Law University",
        "Tamil Nadu Doctor M.G.R. Medical University",
        "Tamil Nadu Veterinary and Animal Sciences University",
        "Tamil University",
        "Tamilnadu College of Engineering",
        "Tata Institute of Fundamental Research - TIFR Mumbai",
        "Tata Institute of Social Sciences",
        "Tatysaheb Kore Institute of Engineering and Technology - Warana",
        "Technocrats Institute of Technology",
        "Technological Institute Of Textile and Sciences",
        "Techno India College of Technology",
        "Teerthanker Mahaveer Institute of Management and Technology",
        "Tezpur University",
        "Thadomal Shahani Engineering College",
        "Thakral College of Technology",
        "Thakur College Of Engeneering And Technology",
        "Thangal Kunju Musaliar College of Engineering - TKM",
        "Thangavelu College",
        "Thapar Institute of Engineering and Technology",
        "The American College",
        "The Heritage Academy",
        "The Maharaja Sayajirao University of Baroda",
        "Theegala Krishna Reddy College of Engineering and Technology",
        "Thiagarajar College of Engineering",
        "Thiagarajar School of Management",
        "Tilak Maharashtra Vidyapeeth",
        "Tilka Manjhi Bhagalpur University",
        "Toc-H Institute of Science and Technology",
        "Tripura University",
        "U. V. Patel College of Engineering",
        "Ujjain Engineering College",
        "Union Christian College",
        "United College of Engineering &amp; Research",
        "United College of Engineering and Research",
        "United Institute of Technology - UIT",
        "University College of Engineering",
        "University Institute of Computer Science and Applications",
        "University Institute of Engineering and Technology - UIET",
        "University Institute of Technology Barkatullah University",
        "UIT RGPV",
        "University Visvesvaraya College of Engineering",
        "University of Agricultural Sciences",
        "University of Burdwan",
        "University of Calcutta",
        "University of Calicut",
        "University of Delhi - University of Delhi",
        "University of Hyderabad",
        "University of Jammu",
        "University of Kalyani",
        "University of Kashmir",
        "University of Kerela",
        "University of Lucknow",
        "University of Madras",
        "University of Mumbai",
        "University of Mysore",
        "University of North Bengal",
        "University of Petroleum and Energy Studies - UPES",
        "University of Pune",
        "University of Rajasthan",
        "University of Roorkee - UP",
        "University of Vishweshwariya College of Engineering",
        "Utkal Sanskruti Viswavidyalaya",
        "Utkal University",
        "Uttam Devi Mohan Lal College of Engineering",
        "Uttar Banga Krishni Viswavidyalaya",
        "Uttar Maharashtra Vidyapeeth",
        "Uttar Pradesh Rajarshi Tandon Open University",
        "Uttar Pradesh Technical University",
        "Uttaranchal Institute of Management",
        "V. H. N. Senthikumaranadar College",
        "V. L. B. Janakiammal College",
        "V. S. Patel College",
        "V.B.S Purvanchal University",
        "V.S.M. College",
        "VEL TECH MULTI TECH Engineering College",
        "VHNSN College",
        "VIF College of Engineering and Technology",
        "VR Siddhartha Engineering College",
        "VRS College of Engineering and Technology - VRSCET",
        "VVV College for Women",
        "Vaagdevi Institute of Technology and Science",
        "Valliammai Engineering College",
        "VNRVJIET",
        "Vardhaman College Of Engineering",
        "Vasavi College of Engineering",
        "Veer Kunwar Singh University",
        "Veer Narmad South Gujarat University",
        "Veer Surendra Sai University Of Technology",
        "Veermata Jijabai Technological Institute",
        "Vel Tech High Tech Dr.Rangarajan Dr.Sakunthala Engineering College",
        "Velammal College of Management and Computer Studies",
        "Velammal Engineering College - VEC",
        "Vellalar College of Engineering and Technology",
        "Vellore Engineering College",
        "Vellore Institute of Technology",
        "Vemana Institute of Technology",
        "Vickram College of Engineering",
        "Vidya Academy of Science and Technology",
        "Vidya Bhawan Rural Institute",
        "Vidya Jyothi Institute of technology - VJIT",
        "Vidya Pratishthan College Of Engineering",
        "Vidyalankar Institute Of Technology",
        "Vidyalankar Polytechnic",
        "Vidyasagar Viswavidyalaya",
        "Vignan Institute of Technology and Science",
        "Vignans Engineering College",
        "Vignana Jyothi College Of Engineering And Technology",
        "Vijetha Degree College",
        "Vikasa Engineering Institute of Technology",
        "Vikram University",
        "Villa Marie P. G. College For Women",
        "Vimal Jyothi Engineering College",
        "Vinayaka Missions Research Foundation - University",
        "Vinoba Bhave University",
        "Vishwakarma Institute of Technology",
        "Visva-Bharati",
        "Visvesvaraya National Institute of Technology",
        "Visvesvaraya Technological University",
        "Visveswaraiah Technological University",
        "Viswajyothi College of Engineering and Technology",
        "Vivekanand Education Society Institute of Technology",
        "Vivekanand Institute of Technology",
        "Vivekananda College of Computer Science",
        "Vivekanandha Institute of Engineering and Technology for Women",
        "Vivekanandha College of Technology for Women",
        "Vivekananda Institute of Technology and Science",
        "Vivekananda Institute of Technology",
        "Vivekananda School of Post Graduate Studies",
        "Walchand College of Engineering",
        "West Bengal National University of Juridical Sciences",
        "West Bengal University of Animal and Fishery Sciences",
        "West Bengal University of Technology",
        "Womens College",
        "XLRI Jamshedpur Business School",
        "Xavier Institute of Management",
        "Xavier Institute of Social Service",
        "Yagyavalkya Institute of Technology - YIT",
        "Yashwantrao Chavan Maharashtra Open University",
        "Yeahwantro Chavan College Of Engineering (YCCE)",
        "Zakir Hussain College of Engg &amp; Technology",
        "Velalar College of Engineering and Technology",
        "Sri Eshwar College Of Engineering",
        "PSG Institute Of Technology and Applied Research",
        "Mahendra Institute of Technology",
        "knowledge institute of technology",
        "seagi",
        "sree vidyanikethan engineering college",
        "Gayatri Vidya Parishad College of engineering for women ",
        "KIT - Kalaignar Karunanidhi Institute of Technology",
        "Info Institute of Engineering",
        "KPR Institute of Engineering and Technology",
        "Sri Sairam Institute of technology",
        "Dr.NGP Institute of technology",
        "PSGR Krishnammal College for Women",
        "Central Institute of Plastic Engineering and Technology",
        "Akshaya College of Engineering and Technology",
        "Sree Sakthi Engineering College",
        "Muthoot Institute of Technology and Science",
        "Indian Institute of Information Technology",
        "Ramco Institute of Technology",
        "Dhirajlal Gandhi College of Technology",
        "Velammal College Of Engineering and Technology",
        "TRP Engineering College",
        "Nandha College of Technology",
        "MIET Engineering College",
        "Christ college of engineering and technology",
        "K. Ramakrishnan College of Technology",
        "Sri Ramakrishna Institute of Technology",
        "Sree Chitra Thirunal College of Engineering",
        "Galaxy Institute of Technology",
        "JCT College of Engineering and Technology",
        "Sri Krishna College of Technology (SKCT)",
        "Daiata Madhusudhana Sastry sri venkateswara hindu Colllege of Engineering",
        "CMF College",
        "CMS College",
        "Kongunadu Institute of Engineering and Technology",
        "bharathi matriculation higher secondary school",
        "Mahatma Gandhi Medical College & Research Institute",
        "SSS Film Academy",
        "Rathinam College of Arts",
        "SSN Institute of Engineering & Technology",
        "sri guru institute of technlogy",
        "Suguna PIP School",
        "Nehru College of Aeronautics & Applied science",
        "SVS College of Engineering",
        "KAP Viswanatham Government Medical College",
        "SSM Institute of Engineering and technology",
        "NGM Arts & Science College",
        "SNS College of Technology",
        "RVS College of engineering and technology",
        "Nehru Institute OF Engineering & Technology",
    ];

    export default collegeList