const data = [
  {
    name: 'Rajdeep Sengupta',
    photo_url: 'https://i.ibb.co/gVX6fmT/rajdeep.jpg',
    designation: 'CEO, co-founder',
    linkedin_url: 'https://www.linkedin.com/in/rajdeep-sengupta/',
    github_url: 'https://github.com/bbsdevloper',
    twitter_url: 'https://twitter.com/MukeshKuiry7',
  },
  {
    name: 'Debajyoti Saha',
    photo_url: 'https://i.ibb.co/k0gXrQ3/Dev.jpg',
    designation: 'CPO, co-founder',
    linkedin_url: 'https://www.linkedin.com/in/debajyotisaha14/',
    github_url: 'https://github.com/bbsdevloper',
    twitter_url: 'https://twitter.com/MukeshKuiry7',
  },
  {
    name: 'Avik Bhuin',
    photo_url: 'https://i.ibb.co/HC36Hvf/Avik.jpg',
    designation: 'COO, co-founder',
    linkedin_url: 'https://www.linkedin.com/in/avik-bhuin-777a77218/',
    github_url: 'https://github.com/bbsdevloper',
    twitter_url: 'https://twitter.com/MukeshKuiry7',
  },
  {
    name: 'Nikhil Raj',
    photo_url: 'https://i.ibb.co/qCmsqPR/nikhil.jpg ',
    designation: 'CTO, co-founder',
    linkedin_url: 'https://www.linkedin.com/in/nikhil25803/',
    github_url: 'https://github.com/bbsdevloper',
    twitter_url: 'https://twitter.com/MukeshKuiry7',
  },
  {
    name: 'Roshan Kumar',
    photo_url: 'https://i.ibb.co/5vNtRXw/roshan.jpg ',
    designation: 'Cheif Designer, co-founder',
    linkedin_url: 'https://www.linkedin.com/in/roshan-kumar-176918202/',
    github_url: 'https://github.com/bbsdevloper',
    twitter_url: 'https://twitter.com/MukeshKuiry7',
  },
  {
    name: 'Subho Ghosh',
    photo_url: 'https://i.ibb.co/WcmnDWx/subho.jpg ',
    designation: 'Social Media Manager, co-founder',
    linkedin_url: 'https://www.linkedin.com/in/thesubhoghosh/',
    github_url: 'https://github.com/bbsdevloper',
    twitter_url: 'https://twitter.com/MukeshKuiry7',
  },
  {
    name: 'Mukesh Kuiry',
    photo_url: 'https://i.ibb.co/jy38SXJ/mkesh.jpg ',
    designation: 'Cheif-Developer',
    linkedin_url: 'https://www.linkedin.com/in/mukeshkuiry/',
    github_url: 'https://github.com/bbsdevloper',
    twitter_url: 'https://twitter.com/MukeshKuiry7',
  },
  {
    name: 'Ravindra Pandey ',
    photo_url: 'https://i.ibb.co/nD5zf3X/ravindra.jpg ',
    designation: 'Cheif-Developer',
    linkedin_url: 'https://www.linkedin.com/in/ravindrap04/',
    github_url: 'https://github.com/RavindraP04',
    twitter_url: 'https://twitter.com/RavindraP04',
  },
  {
    name: 'Muskan',
    photo_url: 'https://i.ibb.co/r2DK3KX/muskan.jpg ',
    designation: 'Co-Designer',
    linkedin_url: 'https://www.linkedin.com/in/muskan-b95b9025b/',
    github_url: 'https://github.com/bbsdevloper',
    twitter_url: 'https://twitter.com/MukeshKuiry7',
  },
  {
    name: 'Monishka Jaiswal',
    photo_url: 'https://i.ibb.co/DgcDXJg/Monishka.jpg ',
    designation: 'Developer',
    linkedin_url: 'https://www.linkedin.com/in/monishka-jaiswal-6aab71239/',
    github_url: 'https://github.com/bbsdevloper',
    twitter_url: 'https://twitter.com/MukeshKuiry7',
  },

  {
    name: 'Akash Jha',
    photo_url: 'https://i.ibb.co/vQvsfCL/akash.jpg ',
    designation: 'Developer',
    linkedin_url: 'https://www.linkedin.com/in/akash-jha-087632230/',
    github_url: 'https://github.com/bbsdevloper',
    twitter_url: 'https://twitter.com/MukeshKuiry7',
  },
];

export default data;
