const data = [
  {
    name: 'Rajdeep Sengupta',
    photo_url: 'https://i.ibb.co/gVX6fmT/rajdeep.jpg',
    designation: 'Co-founder',
    linkedin_url: 'https://www.linkedin.com/in/rajdeep-sengupta/',
    github_url: 'https://github.com/Rajdip019',
    twitter_url: 'https://twitter.com/RajdeepS019',
  },
  {
    name: 'Debajyoti Saha',
    photo_url: 'https://i.ibb.co/k0gXrQ3/Dev.jpg',
    designation: 'Co-founder',
    linkedin_url: 'https://www.linkedin.com/in/debajyotisaha14/',
    github_url: 'https://github.com/Debajyoti14',
    twitter_url: 'https://twitter.com/debajyoti14_',
  },
  {
    name: 'Roshan Kumar',
    photo_url: 'https://i.ibb.co/5vNtRXw/roshan.jpg ',
    designation: 'Co-founder',
    linkedin_url: 'https://www.linkedin.com/in/roshan-kumar-176918202/',
    github_url: 'https://github.com/Roshaen',
    twitter_url: 'https://twitter.com/youhaveme__',
  },
  {
    name: 'Nikhil Raj',
    photo_url: 'https://i.ibb.co/qCmsqPR/nikhil.jpg ',
    designation: 'Co-founder',
    linkedin_url: 'https://www.linkedin.com/in/nikhil25803/',
    github_url: 'https://github.com/nikhil25803',
    twitter_url: 'https://twitter.com/humans_write',
  },
  {
    name: 'Subho Ghosh',
    photo_url: 'https://i.ibb.co/WcmnDWx/subho.jpg ',
    designation: 'Social Media Manager',
    linkedin_url: 'https://www.linkedin.com/in/thesubhoghosh/',
    github_url: 'https://github.com/bbsdevloper',
    twitter_url: 'https://twitter.com/subhoghosh02',
  },
  {
    name: 'Avik Bhuin',
    photo_url: 'https://i.ibb.co/HC36Hvf/Avik.jpg',
    designation: 'Operations Lead',
    linkedin_url: 'https://www.linkedin.com/in/avik-bhuin-777a77218/',
    github_url: '#',
    twitter_url: 'https://twitter.com/Avik_on_web',
  },
  {
    name: 'Mukesh Kuiry',
    photo_url: 'https://i.ibb.co/jy38SXJ/mkesh.jpg ',
    designation: 'Web-Developer',
    linkedin_url: 'https://www.linkedin.com/in/mukeshkuiry/',
    github_url: 'https://github.com/bbsdevloper',
    twitter_url: 'https://twitter.com/MukeshKuiry7',
  },
  {
    name: 'Ravindra Pandey ',
    photo_url: 'https://i.ibb.co/nD5zf3X/ravindra.jpg ',
    designation: 'Web-Developer',
    linkedin_url: 'https://www.linkedin.com/in/ravindrap04/',
    github_url: 'https://github.com/bbsdevloper',
    twitter_url: 'https://twitter.com/ravindraP04',
  },
  {
    name: 'Muskan',
    photo_url: 'https://i.ibb.co/r2DK3KX/muskan.jpg ',
    designation: 'UI/UX Designer',
    linkedin_url: 'https://www.linkedin.com/in/muskan-b95b9025b/',
    github_url: '#',
    twitter_url: '#',
  },
  {
    name: 'Monishka Jaiswal',
    photo_url: 'https://i.ibb.co/DgcDXJg/Monishka.jpg ',
    designation: 'Web-Developer',
    linkedin_url: 'https://www.linkedin.com/in/monishka-jaiswal-6aab71239/',
    github_url: '#',
    twitter_url: '#',
  },
  {
    name: 'Akash Jha',
    photo_url: 'https://i.ibb.co/vQvsfCL/akash.jpg ',
    designation: 'Web-Developer',
    linkedin_url: 'https://www.linkedin.com/in/akash-jha-087632230/',
    github_url: 'https://github.com/bbsdevloper',
    twitter_url: 'https://twitter.com/MukeshKuiry7',
  },
  {
    name: 'Hritik Bhattacharya',
    photo_url: 'https://i.ibb.co/QQhh6Vs/hritik.jpg',
    designation: 'Web-Developer',
    linkedin_url: 'https://www.linkedin.com/in/hritik-bhattacharya-631847210/',
    github_url: 'https://github.com/hritikbhattacharya',
    twitter_url: 'https://twitter.com/Hritikb25',
  },
  {
    name: 'Ashhutosh Jha',
    photo_url: 'https://i.ibb.co/QDDKKF3/ashdude.jpg',
    designation: 'Flutter-Developer',
    linkedin_url: 'https://www.linkedin.com/in/ashhutosh-jha-6734541b9/',
    github_url: 'https://github.com/ashdude1401',
    twitter_url: 'https://twitter.com/Ashutos24857768',
  },
  {
    name: 'Bhavik Kothari',
    photo_url: 'https://i.ibb.co/DMGYNkd/bhavik.jpg',
    designation: 'Flutter-Developer',
    linkedin_url: 'https://www.linkedin.com/in/bhavik-kothari/',
    github_url: '#',
    twitter_url: '#',
  },
];

export default data;
