export const techstack = [
    {name : "HTML"},
    {name : "CSS"},
    {name : "JavaScript"},
    {name : "Node JS"},
    {name : "Android"},
    {name : "Flutter"},
    {name : "Google Cloud"},
    {name : "Python"},
    {name : "C"},
    {name : "C++"},
    {name : "Go"},
    {name : "Solidity"},
    {name : "Bash"},
    {name : "Linux"},
    {name : "Machine Learning"},
    {name : "Tensorflow"},
    {name : "Open CV"},
    {name : "Dart"},
    {name : "Django"},
    {name : "Flask"},
    {name : "FastAPI"},
    {name : "Bootstrap"},
    {name : "Firebase"},
    {name : "MySQL"},
    {name : "Web3"},
    {name : "Cloud Computing"},
    {name : "Deep Learning"},
    {name : "Electron"},
    {name : "GraphQL"},
    {name : "JQuery"},
    {name : "Julia"},
    {name : "Kotlin"},
    {name : "Kubernetes"},
    {name : "Laravel"},
    {name : "MATLAB"},
    {name : "NPL"},
    {name : "Perl"},
    {name : "Qt"},
    {name : "Redux"},
    {name : "Rust"},
    {name : "Ruby"},
    {name : "Aurduino"},
    {name : "Scala"},
    {name : "Unreal Engine"},
    {name : "Wordpress"},
    {name : "Xamarin"},
    {name : "Sketch"},
    {name : "Jenkins"},
    {name : "Raspberry Pi"},
    {name : "React"},
    {name : "Next.js"},
    {name : "Tailwind CSS"},
    {name : "AWS"},
    {name : "Azure"},
    {name : "TypeScript"},
    {name : "Jest"},
    {name : "Chai"},
    {name : "Express"},   
    {name : "Angular"},   
    {name : "Postman"},   
    {name : "MongoDB"},   
    {name : "PostgreSQL"},   
    {name : "LAMP"},   
    {name : "Ruby on Rails"},   
    {name : "NGINX"},   
    {name : "LAMP"},   
    {name : "Spring"},   
    {name : "Vue"},   
    {name : "PHP"},   
    {name : "Docker"},   
    {name : "Swift"},   
    {name : "Android Studio"},   
    {name : "React Native"},   
    {name : "Expo Go"},   
    {name : "CouchDB"},   
    {name : "Kafka"},   
    {name : "Hadoop"},   
    {name : "Yaml"},   
    {name : "Blockchain"},   
    {name : "Ethereum"},   
    {name : "Data Protection"},   
    {name : "Objective C"},   
    {name : ".NET"},   
    {name : "Ember.js"},   
    {name : "BackBone.js"},  
    {name : "jQuery"},  
    {name : "Redis"},  
    {name : "SQL Server"},  
    {name : "Oracle"}, 
]