export const techstack = [
    {name : "HTML"},
    {name : "CSS"},
    {name : "JavaScript"},
    {name : "Node JS"},
    {name : "Android"},
    {name : "Flutter"},
    {name : "Google Cloud"},
    {name : "Python"},
    {name : "C"},
    {name : "C++"},
    {name : "Go"},
    {name : "Solidity"},
    {name : "Bash"},
    {name : "Linux"},
    {name : "Machine Learning"},
    {name : "Tensorflow"},
    {name : "Open CV"},
    {name : "Dart"},
    {name : "Django"},
    {name : "Flask"},
    {name : "FastAPI"},
    {name : "Bootstrap"},
    {name : "Firebase"},
    {name : "MySQL"},
    {name : "Web3"},
    {name : "Cloud Computing"},
    {name : "Deep Learning"},
    {name : "Electron"},
    {name : "GraphQL"},
    {name : "JQuery"},
    {name : "Julia"},
    {name : "Kotlin"},
    {name : "Kubernetes"},
    {name : "Laravel"},
    {name : "MATLAB"},
    {name : "NPL"},
    {name : "Perl"},
    {name : "Qt"},
    {name : "Redux"},
    {name : "Rust"},
    {name : "Ruby"},
    {name : "Aurduino"},
    {name : "Scala"},
    {name : "Unreal Engine"},
    {name : "Wordpress"},
    {name : "Xamarin"},
    {name : "Sketch"},
    {name : "Jenkins"},
    {name : "Raspberry Pi"},
    {name : "React"},
    {name : "Next.js"},
    {name : "Tailwind CSS"},
    {name : "AWS"},
    {name : "Azure"},
    {name : "TypeScript"},
    {name : "Jest"},
    {name : "Chai"},
    {name : "Express"},   
]