export const techstack = [
  { name: '.NET' },
  { name: 'Android' },
  { name: 'Android Studio' },
  { name: 'Angular' },
  { name: 'Aurduino' },
  { name: 'AWS' },
  { name: 'Azure' },
  { name: 'Babel' },
  { name: 'BackBone.js' },
  { name: 'Bash' },
  { name: 'Blockchain' },
  { name: 'Bootstrap' },
  { name: 'C' },
  { name: 'C#' },
  { name: 'C++' },
  { name: 'CanvasJS' },
  { name: 'Carbon' },
  { name: 'Chai' },
  { name: 'ChartJS' },
  { name: 'Clojure' },
  { name: 'Cloud Computing' },
  { name: 'CockroachDb' },
  { name: 'Coffeescript' },
  { name: 'CouchDB' },
  { name: 'CSS' },
  { name: 'Dart' },
  { name: 'Data Protection' },
  { name: 'Deep Learning' },
  { name: 'Django' },
  { name: 'Docker' },
  { name: 'DotNet' },
  { name: 'Electron' },
  { name: 'ElectronJS' },
  { name: 'Elixir' },
  { name: 'Ember.js' },
  { name: 'Erlang' },
  { name: 'Ethereum' },
  { name: 'Expo Go' },
  { name: 'Express' },
  { name: 'FastAPI' },
  { name: 'Firebase' },
  { name: 'Flask' },
  { name: 'Flutter' },
  { name: 'Gatsby' },
  { name: 'Git' },
  { name: 'Go' },
  { name: 'Google Cloud' },
  { name: 'GraphQL' },
  { name: 'Gulp' },
  { name: 'Hadoop' },
  { name: 'Haskell' },
  { name: 'HTML' },
  { name: 'JavaScript' },
  { name: 'Jenkins' },
  { name: 'Jest' },
  { name: 'JQuery' },
  { name: 'jQuery' },
  { name: 'Julia' },
  { name: 'Kafka' },
  { name: 'Kotlin' },
  { name: 'Kubernetes' },
  { name: 'LAMP' },
  { name: 'LAMP' },
  { name: 'Laravel' },
  { name: 'Linux' },
  { name: 'Machine Learning' },
  { name: 'MATLAB' },
  { name: 'Meteor.js' },
  { name: 'MongoDB' },
  { name: 'MySQL' },
  { name: 'Next.js' },
  { name: 'NGINX' },
  { name: 'Nim' },
  { name: 'Node JS' },
  { name: 'NPL' },
  { name: 'NuxtJS' },
  { name: 'Objective C' },
  { name: 'Open CV' },
  { name: 'Oracle' },
  { name: 'Perl' },
  { name: 'PHP' },
  { name: 'PostgreSQL' },
  { name: 'Postman' },
  { name: 'Pug' },
  { name: 'Python' },
  { name: 'Pytorch' },
  { name: 'Qt' },
  { name: 'Quasar' },
  { name: 'Raspberry Pi' },
  { name: 'React' },
  { name: 'React Native' },
  { name: 'Redis' },
  { name: 'Redux' },
  { name: 'Ruby' },
  { name: 'Ruby on Rails' },
  { name: 'Rust' },
  { name: 'Sass' },
  { name: 'Scala' },
  { name: 'Sketch' },
  { name: 'Solidity' },
  { name: 'Spring' },
  { name: 'SQL Server' },
  { name: 'Svelte' },
  { name: 'Swift' },
  { name: 'Tailwind CSS' },
  { name: 'Tensorflow' },
  { name: 'TypeScript' },
  { name: 'Unity' },
  { name: 'Unreal Engine' },
  { name: 'Unrealscript' },
  { name: 'Vue' },
  { name: 'Vuetify' },
  { name: 'Web3' },
  { name: 'WebAssembly' },
  { name: 'Webpack' },
  { name: 'Wordpress' },
  { name: 'Xamarin' },
  { name: 'Yaml' },
];
