import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { styled } from '@mui/material/styles';
import ArrowForwardIosSharpIcon from '@mui/icons-material/ArrowForwardIosSharp';
import MuiAccordion, { AccordionProps } from '@mui/material/Accordion';
import MuiAccordionSummary, { AccordionSummaryProps } from '@mui/material/AccordionSummary';
import MuiAccordionDetails from '@mui/material/AccordionDetails';
import Typography from '@mui/material/Typography';

const Faq: NextPage = () => {

  const Accordion = styled((props: AccordionProps) => (
    <MuiAccordion disableGutters elevation={0} square {...props} />
  ))(({ theme }) => ({
    border: `1px solid ${theme.palette.divider}`,
    '&:not(:last-child)': {
      borderBottom: 0,
    },
    '&:before': {
      display: 'none',
    },
  }));

  const AccordionSummary = styled((props: AccordionSummaryProps) => (
    <MuiAccordionSummary
      expandIcon={<ArrowForwardIosSharpIcon sx={{ fontSize: '0.9rem' }} />}
      {...props}
    />
  ))(({ theme }) => ({
    backgroundColor:
      theme.palette.mode === 'dark'
        ? 'rgba(255, 255, 255, .05)'
        : 'rgba(0, 0, 0, .03)',
    flexDirection: 'row-reverse',
    '& .MuiAccordionSummary-expandIconWrapper.Mui-expanded': {
      transform: 'rotate(90deg)',
    },
    '& .MuiAccordionSummary-content': {
      marginLeft: theme.spacing(1),
    },
  }));

  const AccordionDetails = styled(MuiAccordionDetails)(({ theme }) => ({
    padding: theme.spacing(2),
    borderTop: '1px solid rgba(0, 0, 0, .125)',
  }));

  
  const [expand, setExpand] = React.useState<string | false>('panel1');
  

  const handleChange =
    (panel: string) => (event: React.SyntheticEvent, newExpanded: boolean) => {
      setExpand(newExpanded ? panel : false);
    };


  return (
    <div>
      <Head>
        <title>ClueLess | FAQ</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="w-4/5 m-auto">
        <h1 className="font-raleway text-[28px] md:text-[36px] font-semibold leading-normal my-3 md:text-[28]">
          Having Questions?
          <span className="font-raleway text-skin-main"> Try finding them below </span>:
        </h1>
            <p className="leading-6 text-sm md:text-base my-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit qui, excepturi rerum, ea repellendus molestiae, obcaecati hic eveniet reiciendis cum iusto accusamus. Enim minima inventore soluta, accusantium atque quod. Expedita officiis sapiente enim reiciendis.</p>

            {/* FAQ section */}
        <h1 className="font-raleway text-[28px] md:text-[36px] font-semibold leading-normal my-3 md:text-[28]">FAQ</h1>

        {/* Accordion  */}
        <div>
      <Accordion expanded={expand === 'panel1'} onChange={handleChange('panel1')}>
        <AccordionSummary aria-controls="panel1d-content" id="panel1d-header">
          <Typography>1. Where does these donation goes?</Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse
            malesuada lacus ex, sit amet blandit leo lobortis eget. Lorem ipsum dolor
            sit amet, consectetur adipiscing elit. Suspendisse malesuada lacus ex,
            sit amet blandit leo lobortis eget.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic sit, ipsum laborum velit doloremque, expedita nesciunt eius consectetur, suscipit maiores perspiciatis vitae.
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dicta, asperiores molestiae? Ipsum aliquam in ullam quas incidunt esse, veniam dolorem autem asperiores alias. Neque vero consequuntur iste dolores mollitia libero, velit natus.
          </Typography>
        </AccordionDetails>
      </Accordion>
      <Accordion expanded={expand === 'panel2'} onChange={handleChange('panel2')}>
        <AccordionSummary aria-controls="panel2d-content" id="panel2d-header">
          <Typography> 2. How to sell books?</Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse
            malesuada lacus ex, sit amet blandit leo lobortis eget. Lorem ipsum dolor
            sit amet, consectetur adipiscing elit. Suspendisse malesuada lacus ex,
            sit amet blandit leo lobortis eget.
          </Typography>
        </AccordionDetails>
      </Accordion>
      <Accordion expanded={expand === 'panel3'} onChange={handleChange('panel3')}>
        <AccordionSummary aria-controls="panel3d-content" id="panel3d-header">
          <Typography> 3. Why Invoicing is must?</Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse
            malesuada lacus ex, sit amet blandit leo lobortis eget. Lorem ipsum dolor
            sit amet, consectetur adipiscing elit. Suspendisse malesuada lacus ex,
            sit amet blandit leo lobortis eget.
          </Typography>
        </AccordionDetails>
      </Accordion>
      <Accordion expanded={expand === 'panel4'} onChange={handleChange('panel4')}>
        <AccordionSummary aria-controls="panel1d-content" id="panel1d-header">
          <Typography> 4. How the books are delivered?</Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse
            malesuada lacus ex, sit amet blandit leo lobortis eget. Lorem ipsum dolor
            sit amet, consectetur adipiscing elit. Suspendisse malesuada lacus ex,
            sit amet blandit leo lobortis eget.
          </Typography>
        </AccordionDetails>
      </Accordion>
    </div>


    <div className="my-6 flex items-center">
      <h2 className="text-lg font-semibold mr-3">Have Questions other than this?</h2>
      <button className=" btn-blue">Contact</button>
      </div>
        
        
      </div>
    </div>
  );
};

export default Faq;

