import Head from 'next/head'
import React from 'react'
import Navbar from './components/Navbar/Navbar'
import Footer from './components/Footer'
import ProfileCard from './components/cards/ProfileCard'
import '../database/profileData'
import profile from '../database/profileData'

const aboutUs = () => {
  return (
    <div>
        <Head>
            <title>ClueLess | About Us</title>
            <meta name="description" content="Generated by create next app" />
        </Head>
        <Navbar />

        {/* top section  */}
        <div  className=' bg-skin-main flex justify-center items-center h-[480px]'>
          <div className='flex w-4/5 mx-auto justify-between'>
          <div className='w-full lg:w-1/2 flex flex-col justify-center'>
            <div className='mb-8 text-center lg:text-left'>
            <h1 className=' font-raleway font-bold text-5xl text-white tracking-wider leading-normal'>About</h1>
            <h1 className=' font-raleway font-bold text-5xl text-white tracking-wider'>ClueLess</h1>
            </div>
            <p className='text-[#EDECEC] text-md font-nunito text-center lg:text-left'>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt maxime non illo, repellendus cumque optio delectus ad? Maiores laboriosam at placeat laborum iure rerum earum dolore dignissimos esse sed quo aspernatur sapiente fugiat eius praesentium eum porro voluptatibus pariatur cum dicta quia nulla alias,</p>
          </div>
          <div className='flex justify-center'>
            <img className='hidden lg:block' src="/aboutUsGirl.png" alt=""/>
          </div>
          </div>
        </div>
        {/* our vision */}

        <div className='h-[430px] md:h-[280px] flex flex-col justify-evenly items-center w-4/5 mx-auto mb-7'>
            <h1 className='font-raleway font-bold text-3xl sm:text-5xl my-5'>Our Vision🚀</h1>
            <p className='text-center text-sm w-4/5 text-[#111111]'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni numquam natus mollitia. Perferendis, consequuntur vitae voluptatum officia veniam quia magnam explicabo aliquam, eius impedit provident omnis pariatur doloremque non similique rem, odit accusantium reiciendis veritatis! Maxime voluptate nihil ut dolores deserunt sed, culpa perspiciatis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis quam mollitia, cum corporis ipsam officiis, accusamus temporibus doloribus, ex debitis vitae consequuntur accusantium! </p>
        </div>
        <h1 className='font-raleway font-bold text-3xl sm:text-5xl text-center my-8 '>Team Members✨</h1>

        <div className="flex flex-wrap w-10/12 mx-auto justify-center">
          {profile.map((profiles)=>{
            return (
              <div className='m-12'>
              <ProfileCard
                key={profiles.id}
                img={profiles.img}
                username={profiles.name}
                tag={profiles.tags}
                about={profiles.about}
                github={profiles.github}
                linkedin={profiles.linkedin}
                twitter={profiles.twitter}
              />
              </div>
            );
          })}
          </div>

          <div className='flex my-24 w-10/12 flex-col-reverse items-center sm:justify-between mx-auto md:flex-row'>
            <div className='w-[40%] justify-end items-center md:flex'>
              <img className='w-72 mt-10 md:mt-0' src="/cactus.png" alt=""  />
            </div>
            <div className='w-[80%]  md:w-[60%] flex flex-col justify-center text-center md:text-left mx-auto md:mx-0'>
              <p className=' font-nunito w-[100%]  md:w-[80%] text-sm text-[#5B5B5B]'>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Pariatur sequi voluptas neque impedit vitae doloribus sapiente. Iste deleniti eos dolore voluptatem nisi hic consequatur excepturi distinctio, incidunt ut magni commodi provident dolores omnis cum. Nam neque dolor molestias nihil nisi. Inventore maiores non reiciendis ipsam!</p>
              <br />
              <p className=' font-nunito w-[80%] text-sm text-[#5B5B5B] mx-auto md:mx-0'>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia tempora, nam minima quidem ex odio beatae non sequi quos eos quae laborum?</p>
            </div>
          </div>   

          <div className='bg-skin-main h-[400px] flex flex-col justify-center items-center'>
              
                <h1 className=' font-raleway font-semibold text-3xl text-white my-4'>Checkout More</h1>
                <p className='font-raleway text-white text-center w-[60%] my-4'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam, accusamus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum dolor eum doloremque dignissimos ipsam, minus, sit officia assumenda, explicabo repudiandae quo ab.</p>
                <button className='border-2 px-3 py-1 text-white rounded-md my-5'>Get Started</button>
            
          </div>


        <Footer />
    </div>
  )
}

export default aboutUs