import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "./components/Navbar/Navbar";
import WhatIsClueLess from "./components/WhatIsClueless/WhatIsClueLess";
import UltimateResourceHub from "./components/UltimateResourceHub/UltimateResourceHub";
import Footer from "./components/Footer";
import TeamMembersHome from "./components/TeamMembersHome/TeamMembersHome";
import DonateHome from "./components/DonateHome/DonateHome";
import HomeMain from "./components/Home/HomeMain";
import AdminpanelChallenge from "./components/cards/AdminPanelChallenge";
import ChallengeCardActive from "./components/cards/ChallengeCardActive";
import ChallengeCardAdmin from "./components/cards/ChallengeCardAdmin";
import AdminpanelPreviousChallenge from "./components/cards/AdminpanelPreviousChallenge";
import ProjectCard from "./components/cards/ProjectCard";
import ResourceCard from "./components/cards/ResourceCard";
import ResourceCardAdmin from "./components/cards/ResourceCardAdmin";
import ChallengeCardPrevious from "./components/cards/ChallengeCardPrevious";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>ClueLess</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      {/* <AdminpanelChallenge img={"/cluelessdog404.png"} title={"Github Student Challenge"} xp={500} time={"25-27 Mar"}/> */}
      {/* <AdminpanelPreviousChallenge img={""} title={""} description={""} /> */}
      <ChallengeCardActive img={"/cluelessdog404.png"} title={"Github Student Challenges"} xp={0} time={"25-27 Mar"}/>
      {/* <ChallengeCardPrevious img={""} title={""} description={""}/> */}
      {/* <ChallengeCardAdmin img={""} title={""} stack={""}/>
      <ProjectCard img={""} title={""} stack={""}/>
      <ResourceCard img={""} title={""} xp={0} category={""} price={""}/>
      <ResourceCardAdmin img={""} title={""} xp={0} category={""} price={""}/> */}
      <HomeMain />
      <WhatIsClueLess />
      <UltimateResourceHub />
      <TeamMembersHome />
      <DonateHome />
      <Footer />
    </div>
  );
};

export default Home;
