import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from './components/Navbar/Navbar'
import WhatIsClueLess from './components/WhatIsClueless/WhatIsClueLess'
import UltimateResourceHub from './components/UltimateResourceHub/UltimateResourceHub'
import Footer from './components/Footer'
import TeamMembersHome from './components/TeamMembersHome/TeamMembersHome'
import DonateHome from './components/DonateHome/DonateHome'
import ResourceCard from './components/cards/ResourceCard'
import ResourceCardAdmin from './components/cards/ResourceCardAdmin'
import ProjectCard from './components/cards/ProjectCard'
import ChallengeCardActive from './components/cards/ChallengeCardActive'
import AdminpanelChallenge from './components/cards/AdminPanelChallenge'
import AdminpanelPreviousChallenge from './components/cards/AdminpanelPreviousChallenge'
import ChallengeCardPrevious from './components/cards/ChallengeCardPrevious'
import ChallengeCardAdmin from './components/cards/ChallengeCardAdmin'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
      <title>ClueLess</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <WhatIsClueLess />
      <UltimateResourceHub />
      <TeamMembersHome />
      <DonateHome />
      <Footer />

    </div>
  )
}

export default Home
