import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from './components/Navbar/Navbar'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
      <title>ClueLess</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
    </div>
  )
}

export default Home
