import { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import Navbar from '../components/Navbar/Navbar'

const Resources: NextPage = () => {
  return (
    <div>
        <Head>
        <title>ClueLess | Resources</title>
        <meta name="description" content="Generated by create next app" />
        </Head>
        <Navbar />
    </div>
  )
}

export default Resources